apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: helloworld-virtualservice
spec:
  hosts:
  - "*"
  gateways:
    - istio-system/istio-ingressgateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld-service
        port:
          number: 5000